apiVersion: v1
kind: Pod
metadata:
  name: counter-server
spec:
   containers:
   - name: counter-server
     image: yysm1990/counter
     ports:
       - containerPort: 8080
         hostPort: 8080
     imagePullPolicy: Always

