apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-server
  labels:
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter-server
        image: sunjing70217/counter
        ports:
          - containerPort: 8080
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: counter-server
  labels:
    app: counter
spec:
  type: NodePort
  selector:
    app: counter
  ports:
    - port: 8080
